parameters:
    inline_sections: ['keywords']

services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Symplify\ComposerJsonManipulator\ComposerJsonFactory: null
    Symplify\ComposerJsonManipulator\FileSystem\JsonFileManager: null

    Symfony\Component\Filesystem\Filesystem: null
    Symplify\PackageBuilder\Reflection\PrivatesCaller: null
